[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
bank = "53ciRQMLYWmkCdwby5BK61SNjYoagkzUhHyEYuWXq956"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/mnt/c/Users/MASTER/Desktop/projects/solana/solana_my_project/gif_portal/solana_tut/anchorProjects/bank/id.json+"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
